import { useQuery } from "@apollo/client";
import { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useState } from "react";
import Locations from "../components/conferenceDetails/Locations";
import Organizer from "../components/conferenceDetails/Organizer";
import Schedule from "../components/conferenceDetails/Schedule";
import Sidebar from "../components/conferenceDetails/Sidebar";
import Speakers from "../components/conferenceDetails/Speakers";
import Sponsors from "../components/conferenceDetails/Sponsors";
import Typography from "../components/shared/Typography";
import GET_CONFERENCE from "../services/conference.service";

const Conference: NextPage = () => {
  const [activeNav, setActiveNav] = useState<String>("speakers");

  const { conferenceID } = useRouter().query;

  const { loading, data } = useQuery(GET_CONFERENCE, {
    variables: { conferenceID },
  });

  return (
    <div className="max-w-[1320px] mx-auto px-16 py-20">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {loading ? (
        <div className="text-center">
          <h3>Loading...</h3>
        </div>
      ) : (
        <>
          <Typography.H2>Conference info</Typography.H2>
          <Typography.H3>
            Lorem uis diam turpis quam id fermentum.In quis diam turpis quam id fermentum.
          </Typography.H3>
          <section className="mt-10 flex gap-10 ">
            <Sidebar setActiveNav={setActiveNav} activeNav={activeNav} />
            <div className="flex-1 bg-[url('/con-detail-bg.png')] p-10 rounded-lg tablet:hidden">
              {activeNav === "speakers" && <Speakers payload={data?.conference?.speakers} />}
              {activeNav === "organizer" && <Organizer />}
              {activeNav === "location" && <Locations />}
              {activeNav === "schedule" && <Schedule />}
              {activeNav === "sponsors" && <Sponsors />}
            </div>
          </section>
        </>
      )}
    </div>
  );
};

export default Conference;
