import Head from "next/head";
import HeroSection from "../components/landingPage/HeroSection";
import TopBar from "../layout/TopBar";

export default function Home() {
  return (
    <div className="bg-[url('/landing-bg.png')] ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <TopBar />
        <HeroSection />
      </div>
    </div>
  );
}
