import { NextPage } from "next";
import Head from "next/head";
import { useQuery } from "react-query";
import EventSchedule from "../components/landingPage/EventSchedule";
import HeroSection from "../components/landingPage/HeroSection";
import Typography from "../components/shared/Typography";
import { getConferences } from "../services/fetchConferences";

const Home: NextPage = () => {
  const { isLoading, data, error } = useQuery("conferences", () => getConferences());

  // console.log(isLoading, data, error);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isLoading ? (
        <div className="h-screen flex items-center justify-center">PLease Wait...</div>
      ) : (
        <div>
          <HeroSection />
          <section className="px-32 py-20">
            <Typography.H2>Event Schedule</Typography.H2>
            <Typography.H3>
              Lorem uis diam turpis quam id fermentum.In quis diam turpis quam id fermentum.
            </Typography.H3>
            <EventSchedule conferences={data.conferences} />
          </section>
        </div>
      )}
    </div>
  );
};

export default Home;
